### ISSUE TITLE
PDF conversion not working 

### ISSUE THREAD

**Issue by MYehia565** [matecat/MateCat-Win-Converter#1]
Hi 

when try to upload pdf file to matecat it sends to MateCat-Win-Converter but at converter it through this error 

"03:23:17 ERROR [5] (ConversionRequest) exception
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.UploadFile(Uri address, String method, String fileName)
   at System.Net.WebClient.UploadFile(String address, String fileName)
   at Translated.MateCAT.WinConverter.Converters.RegularPdfConverter.Convert(String sourceFilePath, Int32 sourceFormat, String targetFilePath, Int32 targetFormat) in C:\Users\Administrator\Downloads\MateCat-Win-Converter\Source\Converters\RegularPdfConverter.cs:line 34
   at Translated.MateCAT.WinConverter.Converters.ConvertersRouter.Convert(String sourceFilePath, Int32 sourceFormat, String targetFilePath, Int32 targetFormat) in C:\Users\Administrator\Downloads\MateCat-Win-Converter\Source\Converters\ConvertersRouter.cs:line 37
   at Translated.MateCAT.WinConverter.ConversionServer.ConversionRequest.Run(Object stateInfo) in C:\Users\Administrator\Downloads\MateCat-Win-Converter\Source\ConversionServer\ConversionRequest.cs:line 131"

and back in matecat it through "Received status code 400"

I doubled checked the API key even i tried another account also and it is not worked 

Thanks for your work

My greetings.

**Comment by giusilvano** [comment]
Hi! I'm sorry I didn't catch this issue for so long, but finally here I am! :)
Can you confirm me that you created an account on CloudConvert , got a personal API key and added it to your App.config file? Also please confirm me that you didn't add this information to the App.sample.config file, but on a App.config file obtained copying App.sample.config.
Let me know, and sorry again for the delay!

**Comment by MYehia565** [comment]
Yes i added the API Key correctly and it was working before

**Comment by giusilvano** [comment]
Very strange... 

We are using this same code in our production system and it is working properly, so I can assure you that the code is updated and the communication protocol with CloudConvert is correct.

The error you reported points to networking or configuration problems, because you can see that the code is properly using the network but it hangs on the Forbidden message that receives from the server.

Unfortunately I don't know how to help you more than asking to investigate more on your network and configuration.

**Comment by giusilvano** [comment]
I close the issue for inactivity. @MYehia565 please feel free to add any other detail you find relevant. Thanks.
